GET http://localhost:8800/register/taitai12345

###
GET  http://localhost:8800/account

###
POST http://localhost:8800/account
Content-Type: application/json

{
    "userName": "taitai31",
    "password": "12345",
    "accountType": "user",
    "image": "./sfgfg/sfg.png"
}
###
GET http://localhost:8800/login/taitai12345
# Content-Type: application/json

# {
#     "password": "12345",
# }