export const SELECTED_PLACES_SUCCES = "SELECTED_PLACES_SUCCES"
export const SELECTED_PLACES_FAIL = "SELECTED_PLACES_FAIL"
export const SELECTED_PLACES_REQUEST = "SELECTED_PLACES_REQUEST"

export const SELECTED_WEATHER_SUCCES = "SELECTED_WEATHER_SUCCES"
export const SELECTED_WEATHER_FAIL = "SELECTED_WEATHER_FAIL"
export const SELECTED_WEATHER_REQUEST = "SELECTED_WEATHER_REQUEST"